export const FETCH_ATTENDANCES_REQUEST = "FETCH_ATTENDANCES_REQUEST";
export const FETCH_ATTENDANCES_SUCCESS = "FETCH_ATTENDANCES_SUCCESS";
export const FETCH_ATTENDANCES_FAIL = "FETCH_ATTENDANCES_FAIL";

export const FETCH_ATTENDANCE_REQUEST = "FETCH_ATTENDANCE_REQUEST";
export const FETCH_ATTENDANCE_SUCCESS = "FETCH_ATTENDANCE_SUCCESS";
export const FETCH_ATTENDANCE_FAIL = "FETCH_ATTENDANCE_FAIL";
export const FETCH_ATTENDANCE_RESET = "FETCH_ATTENDANCE_RESET";

export const ADD_ATTENDANCE_REQUEST = "ADD_ATTENDANCE_REQUEST";
export const ADD_ATTENDANCE_SUCCESS = "ADD_ATTENDANCE_SUCCESS";
export const ADD_ATTENDANCE_FAIL = "ADD_ATTENDANCE_FAIL";
export const ADD_ATTENDANCE_RESET = "ADD_ATTENDANCE_RESET";

export const UPDATE_ATTENDANCE_REQUEST = "UPDATE_ATTENDANCE_REQUEST";
export const UPDATE_ATTENDANCE_SUCCESS = "UPDATE_ATTENDANCE_SUCCESS";
export const UPDATE_ATTENDANCE_FAIL = "UPDATE_ATTENDANCE_FAIL";
export const UPDATE_ATTENDANCE_RESET = "UPDATE_ATTENDANCE_RESET";

export const DELETE_ATTENDANCE_REQUEST = "DELETE_ATTENDANCE_REQUEST";
export const DELETE_ATTENDANCE_SUCCESS = "DELETE_ATTENDANCE_SUCCESS";
export const DELETE_ATTENDANCE_FAIL = "DELETE_ATTENDANCE_FAIL";
export const DELETE_ATTENDANCE_RESET = "DELETE_ATTENDANCE_RESET";
