export const FETCH_CROPS_REQUEST = "FETCH_CROPS_REQUEST";
export const FETCH_CROPS_SUCCESS = "FETCH_CROPS_SUCCESS";
export const FETCH_CROPS_FAIL = "FETCH_CROPS_FAIL";

export const FETCH_CROP_REQUEST = "FETCH_CROP_REQUEST";
export const FETCH_CROP_SUCCESS = "FETCH_CROP_SUCCESS";
export const FETCH_CROP_FAIL = "FETCH_CROP_FAIL";
export const FETCH_CROP_RESET = "FETCH_CROP_RESET";

export const ADD_CROP_REQUEST = "ADD_CROP_REQUEST";
export const ADD_CROP_SUCCESS = "ADD_CROP_SUCCESS";
export const ADD_CROP_FAIL = "ADD_CROP_FAIL";
export const ADD_CROP_RESET = "ADD_CROP_RESET";

export const UPDATE_CROP_REQUEST = "UPDATE_CROP_REQUEST";
export const UPDATE_CROP_SUCCESS = "UPDATE_CROP_SUCCESS";
export const UPDATE_CROP_FAIL = "UPDATE_CROP_FAIL";
export const UPDATE_CROP_RESET = "UPDATE_CROP_RESET";

export const DELETE_CROP_REQUEST = "DELETE_CROP_REQUEST";
export const DELETE_CROP_SUCCESS = "DELETE_CROP_SUCCESS";
export const DELETE_CROP_FAIL = "DELETE_CROP_FAIL";
export const DELETE_CROP_RESET = "DELETE_CROP_RESET";
