export const FETCH_EXPENSE_CATEGORIES_REQUEST =
  "FETCH_EXPENSE_CATEGORIES_REQUEST";
export const FETCH_EXPENSE_CATEGORIES_SUCCESS =
  "FETCH_EXPENSE_CATEGORIES_SUCCESS";
export const FETCH_EXPENSE_CATEGORIES_FAIL = "FETCH_EXPENSE_CATEGORIES_FAIL";

export const FETCH_EXPENSE_CATEGORY_REQUEST = "FETCH_EXPENSE_CATEGORY_REQUEST";
export const FETCH_EXPENSE_CATEGORY_SUCCESS = "FETCH_EXPENSE_CATEGORY_SUCCESS";
export const FETCH_EXPENSE_CATEGORY_FAIL = "FETCH_EXPENSE_CATEGORY_FAIL";
export const FETCH_EXPENSE_CATEGORY_RESET = "FETCH_EXPENSE_CATEGORY_RESET";

export const ADD_EXPENSE_CATEGORY_REQUEST = "ADD_EXPENSE_CATEGORY_REQUEST";
export const ADD_EXPENSE_CATEGORY_SUCCESS = "ADD_EXPENSE_CATEGORY_SUCCESS";
export const ADD_EXPENSE_CATEGORY_FAIL = "ADD_EXPENSE_CATEGORY_FAIL";
export const ADD_EXPENSE_CATEGORY_RESET = "ADD_EXPENSE_CATEGORY_RESET";

export const UPDATE_EXPENSE_CATEGORY_REQUEST =
  "UPDATE_EXPENSE_CATEGORY_REQUEST";
export const UPDATE_EXPENSE_CATEGORY_SUCCESS =
  "UPDATE_EXPENSE_CATEGORY_SUCCESS";
export const UPDATE_EXPENSE_CATEGORY_FAIL = "UPDATE_EXPENSE_CATEGORY_FAIL";
export const UPDATE_EXPENSE_CATEGORY_RESET = "UPDATE_EXPENSE_CATEGORY_RESET";

export const DELETE_EXPENSE_CATEGORY_REQUEST =
  "DELETE_EXPENSE_CATEGORY_REQUEST";
export const DELETE_EXPENSE_CATEGORY_SUCCESS =
  "DELETE_EXPENSE_CATEGORY_SUCCESS";
export const DELETE_EXPENSE_CATEGORY_FAIL = "DELETE_EXPENSE_CATEGORY_FAIL";
export const DELETE_EXPENSE_CATEGORY_RESET = "DELETE_EXPENSE_CATEGORY_RESET";
