export const FETCH_FIELDS_REQUEST = "FETCH_FIELDS_REQUEST";
export const FETCH_FIELDS_SUCCESS = "FETCH_FIELDS_SUCCESS";
export const FETCH_FIELDS_FAIL = "FETCH_FIELDS_FAIL";

export const FETCH_FIELD_REQUEST = "FETCH_FIELD_REQUEST";
export const FETCH_FIELD_SUCCESS = "FETCH_FIELD_SUCCESS";
export const FETCH_FIELD_FAIL = "FETCH_FIELD_FAIL";
export const FETCH_FIELD_RESET = "FETCH_FIELD_RESET";

export const ADD_FIELD_REQUEST = "ADD_FIELD_REQUEST";
export const ADD_FIELD_SUCCESS = "ADD_FIELD_SUCCESS";
export const ADD_FIELD_FAIL = "ADD_FIELD_FAIL";
export const ADD_FIELD_RESET = "ADD_FIELD_RESET";

export const UPDATE_FIELD_REQUEST = "UPDATE_FIELD_REQUEST";
export const UPDATE_FIELD_SUCCESS = "UPDATE_FIELD_SUCCESS";
export const UPDATE_FIELD_FAIL = "UPDATE_FIELD_FAIL";
export const UPDATE_FIELD_RESET = "UPDATE_FIELD_RESET";

export const DELETE_FIELD_REQUEST = "DELETE_FIELD_REQUEST";
export const DELETE_FIELD_SUCCESS = "DELETE_FIELD_SUCCESS";
export const DELETE_FIELD_FAIL = "DELETE_FIELD_FAIL";
export const DELETE_FIELD_RESET = "DELETE_FIELD_RESET";
