export const FETCH_HARVESTS_REQUEST = "FETCH_HARVESTS_REQUEST";
export const FETCH_HARVESTS_SUCCESS = "FETCH_HARVESTS_SUCCESS";
export const FETCH_HARVESTS_FAIL = "FETCH_HARVESTS_FAIL";

export const FETCH_HARVEST_REQUEST = "FETCH_HARVEST_REQUEST";
export const FETCH_HARVEST_SUCCESS = "FETCH_HARVEST_SUCCESS";
export const FETCH_HARVEST_FAIL = "FETCH_HARVEST_FAIL";
export const FETCH_HARVEST_RESET = "FETCH_HARVEST_RESET";

export const ADD_HARVEST_REQUEST = "ADD_HARVEST_REQUEST";
export const ADD_HARVEST_SUCCESS = "ADD_HARVEST_SUCCESS";
export const ADD_HARVEST_FAIL = "ADD_HARVEST_FAIL";
export const ADD_HARVEST_RESET = "ADD_HARVEST_RESET";

export const UPDATE_HARVEST_REQUEST = "UPDATE_HARVEST_REQUEST";
export const UPDATE_HARVEST_SUCCESS = "UPDATE_HARVEST_SUCCESS";
export const UPDATE_HARVEST_FAIL = "UPDATE_HARVEST_FAIL";
export const UPDATE_HARVEST_RESET = "UPDATE_HARVEST_RESET";

export const DELETE_HARVEST_REQUEST = "DELETE_HARVEST_REQUEST";
export const DELETE_HARVEST_SUCCESS = "DELETE_HARVEST_SUCCESS";
export const DELETE_HARVEST_FAIL = "DELETE_HARVEST_FAIL";
export const DELETE_HARVEST_RESET = "DELETE_HARVEST_RESET";
