export const FETCH_INCOME_CATEGORIES_REQUEST =
  "FETCH_INCOME_CATEGORIES_REQUEST";
export const FETCH_INCOME_CATEGORIES_SUCCESS =
  "FETCH_INCOME_CATEGORIES_SUCCESS";
export const FETCH_INCOME_CATEGORIES_FAIL = "FETCH_INCOME_CATEGORIES_FAIL";

export const FETCH_INCOME_CATEGORY_REQUEST = "FETCH_INCOME_CATEGORY_REQUEST";
export const FETCH_INCOME_CATEGORY_SUCCESS = "FETCH_INCOME_CATEGORY_SUCCESS";
export const FETCH_INCOME_CATEGORY_FAIL = "FETCH_INCOME_CATEGORY_FAIL";
export const FETCH_INCOME_CATEGORY_RESET = "FETCH_INCOME_CATEGORY_RESET";

export const ADD_INCOME_CATEGORY_REQUEST = "ADD_INCOME_CATEGORY_REQUEST";
export const ADD_INCOME_CATEGORY_SUCCESS = "ADD_INCOME_CATEGORY_SUCCESS";
export const ADD_INCOME_CATEGORY_FAIL = "ADD_INCOME_CATEGORY_FAIL";
export const ADD_INCOME_CATEGORY_RESET = "ADD_INCOME_CATEGORY_RESET";

export const UPDATE_INCOME_CATEGORY_REQUEST = "UPDATE_INCOME_CATEGORY_REQUEST";
export const UPDATE_INCOME_CATEGORY_SUCCESS = "UPDATE_INCOME_CATEGORY_SUCCESS";
export const UPDATE_INCOME_CATEGORY_FAIL = "UPDATE_INCOME_CATEGORY_FAIL";
export const UPDATE_INCOME_CATEGORY_RESET = "UPDATE_INCOME_CATEGORY_RESET";

export const DELETE_INCOME_CATEGORY_REQUEST = "DELETE_INCOME_CATEGORY_REQUEST";
export const DELETE_INCOME_CATEGORY_SUCCESS = "DELETE_INCOME_CATEGORY_SUCCESS";
export const DELETE_INCOME_CATEGORY_FAIL = "DELETE_INCOME_CATEGORY_FAIL";
export const DELETE_INCOME_CATEGORY_RESET = "DELETE_INCOME_CATEGORY_RESET";
