export const FETCH_INCOMES_REQUEST = "FETCH_INCOMES_REQUEST";
export const FETCH_INCOMES_SUCCESS = "FETCH_INCOMES_SUCCESS";
export const FETCH_INCOMES_FAIL = "FETCH_INCOMES_FAIL";

export const FETCH_INCOME_REQUEST = "FETCH_INCOME_REQUEST";
export const FETCH_INCOME_SUCCESS = "FETCH_INCOME_SUCCESS";
export const FETCH_INCOME_FAIL = "FETCH_INCOME_FAIL";
export const FETCH_INCOME_RESET = "FETCH_INCOME_RESET";

export const ADD_INCOME_REQUEST = "ADD_INCOME_REQUEST";
export const ADD_INCOME_SUCCESS = "ADD_INCOME_SUCCESS";
export const ADD_INCOME_FAIL = "ADD_INCOME_FAIL";
export const ADD_INCOME_RESET = "ADD_INCOME_RESET";

export const UPDATE_INCOME_REQUEST = "UPDATE_INCOME_REQUEST";
export const UPDATE_INCOME_SUCCESS = "UPDATE_INCOME_SUCCESS";
export const UPDATE_INCOME_FAIL = "UPDATE_INCOME_FAIL";
export const UPDATE_INCOME_RESET = "UPDATE_INCOME_RESET";

export const DELETE_INCOME_REQUEST = "DELETE_INCOME_REQUEST";
export const DELETE_INCOME_SUCCESS = "DELETE_INCOME_SUCCESS";
export const DELETE_INCOME_FAIL = "DELETE_INCOME_FAIL";
export const DELETE_INCOME_RESET = "DELETE_INCOME_RESET";
