export const FETCH_PLANTINGS_REQUEST = "FETCH_PLANTINGS_REQUEST";
export const FETCH_PLANTINGS_SUCCESS = "FETCH_PLANTINGS_SUCCESS";
export const FETCH_PLANTINGS_FAIL = "FETCH_PLANTINGS_FAIL";

export const FETCH_PLANTING_REQUEST = "FETCH_PLANTING_REQUEST";
export const FETCH_PLANTING_SUCCESS = "FETCH_PLANTING_SUCCESS";
export const FETCH_PLANTING_FAIL = "FETCH_PLANTING_FAIL";
export const FETCH_PLANTING_RESET = "FETCH_PLANTING_RESET";

export const ADD_PLANTING_REQUEST = "ADD_PLANTING_REQUEST";
export const ADD_PLANTING_SUCCESS = "ADD_PLANTING_SUCCESS";
export const ADD_PLANTING_FAIL = "ADD_PLANTING_FAIL";
export const ADD_PLANTING_RESET = "ADD_PLANTING_RESET";

export const UPDATE_PLANTING_REQUEST = "UPDATE_PLANTING_REQUEST";
export const UPDATE_PLANTING_SUCCESS = "UPDATE_PLANTING_SUCCESS";
export const UPDATE_PLANTING_FAIL = "UPDATE_PLANTING_FAIL";
export const UPDATE_PLANTING_RESET = "UPDATE_PLANTING_RESET";

export const DELETE_PLANTING_REQUEST = "DELETE_PLANTING_REQUEST";
export const DELETE_PLANTING_SUCCESS = "DELETE_PLANTING_SUCCESS";
export const DELETE_PLANTING_FAIL = "DELETE_PLANTING_FAIL";
export const DELETE_PLANTING_RESET = "DELETE_PLANTING_RESET";
