export const FETCH_STOCKS_REQUEST = "FETCH_STOCKS_REQUEST";
export const FETCH_STOCKS_SUCCESS = "FETCH_STOCKS_SUCCESS";
export const FETCH_STOCKS_FAIL = "FETCH_STOCKS_FAIL";

export const FETCH_STOCK_REQUEST = "FETCH_STOCK_REQUEST";
export const FETCH_STOCK_SUCCESS = "FETCH_STOCK_SUCCESS";
export const FETCH_STOCK_FAIL = "FETCH_STOCK_FAIL";
export const FETCH_STOCK_RESET = "FETCH_STOCK_RESET";

export const ADD_STOCK_REQUEST = "ADD_STOCK_REQUEST";
export const ADD_STOCK_SUCCESS = "ADD_STOCK_SUCCESS";
export const ADD_STOCK_FAIL = "ADD_STOCK_FAIL";
export const ADD_STOCK_RESET = "ADD_STOCK_RESET";

export const UPDATE_STOCK_REQUEST = "UPDATE_STOCK_REQUEST";
export const UPDATE_STOCK_SUCCESS = "UPDATE_STOCK_SUCCESS";
export const UPDATE_STOCK_FAIL = "UPDATE_STOCK_FAIL";
export const UPDATE_STOCK_RESET = "UPDATE_STOCK_RESET";

export const DELETE_STOCK_REQUEST = "DELETE_STOCK_REQUEST";
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS";
export const DELETE_STOCK_FAIL = "DELETE_STOCK_FAIL";
export const DELETE_STOCK_RESET = "DELETE_STOCK_RESET";
