export const FETCH_TREATMENTS_REQUEST = "FETCH_TREATMENTS_REQUEST";
export const FETCH_TREATMENTS_SUCCESS = "FETCH_TREATMENTS_SUCCESS";
export const FETCH_TREATMENTS_FAIL = "FETCH_TREATMENTS_FAIL";

export const FETCH_TREATMENT_REQUEST = "FETCH_TREATMENT_REQUEST";
export const FETCH_TREATMENT_SUCCESS = "FETCH_TREATMENT_SUCCESS";
export const FETCH_TREATMENT_FAIL = "FETCH_TREATMENT_FAIL";
export const FETCH_TREATMENT_RESET = "FETCH_TREATMENT_RESET";

export const ADD_TREATMENT_REQUEST = "ADD_TREATMENT_REQUEST";
export const ADD_TREATMENT_SUCCESS = "ADD_TREATMENT_SUCCESS";
export const ADD_TREATMENT_FAIL = "ADD_TREATMENT_FAIL";
export const ADD_TREATMENT_RESET = "ADD_TREATMENT_RESET";

export const UPDATE_TREATMENT_REQUEST = "UPDATE_TREATMENT_REQUEST";
export const UPDATE_TREATMENT_SUCCESS = "UPDATE_TREATMENT_SUCCESS";
export const UPDATE_TREATMENT_FAIL = "UPDATE_TREATMENT_FAIL";
export const UPDATE_TREATMENT_RESET = "UPDATE_TREATMENT_RESET";

export const DELETE_TREATMENT_REQUEST = "DELETE_TREATMENT_REQUEST";
export const DELETE_TREATMENT_SUCCESS = "DELETE_TREATMENT_SUCCESS";
export const DELETE_TREATMENT_FAIL = "DELETE_TREATMENT_FAIL";
export const DELETE_TREATMENT_RESET = "DELETE_TREATMENT_RESET";
