export const FETCH_VARIETIES_REQUEST = "FETCH_VARIETIES_REQUEST";
export const FETCH_VARIETIES_SUCCESS = "FETCH_VARIETIES_SUCCESS";
export const FETCH_VARIETIES_FAIL = "FETCH_VARIETIES_FAIL";

export const FETCH_VARIETY_REQUEST = "FETCH_VARIETY_REQUEST";
export const FETCH_VARIETY_SUCCESS = "FETCH_VARIETY_SUCCESS";
export const FETCH_VARIETY_FAIL = "FETCH_VARIETY_FAIL";
export const FETCH_VARIETY_RESET = "FETCH_VARIETY_RESET";

export const FETCH_VARIETY_BY_CROP_REQUEST = "FETCH_VARIETY_BY_CROP_REQUEST";
export const FETCH_VARIETY_BY_CROP_SUCCESS = "FETCH_VARIETY_BY_CROP_SUCCESS";
export const FETCH_VARIETY_BY_CROP_FAIL = "FETCH_VARIETY_BY_CROP_FAIL";
export const FETCH_VARIETY_BY_CROP_RESET = "FETCH_VARIETY_BY_CROP_RESET";

export const ADD_VARIETY_REQUEST = "ADD_VARIETY_REQUEST";
export const ADD_VARIETY_SUCCESS = "ADD_VARIETY_SUCCESS";
export const ADD_VARIETY_FAIL = "ADD_VARIETY_FAIL";
export const ADD_VARIETY_RESET = "ADD_VARIETY_RESET";

export const UPDATE_VARIETY_REQUEST = "UPDATE_VARIETY_REQUEST";
export const UPDATE_VARIETY_SUCCESS = "UPDATE_VARIETY_SUCCESS";
export const UPDATE_VARIETY_FAIL = "UPDATE_VARIETY_FAIL";
export const UPDATE_VARIETY_RESET = "UPDATE_VARIETY_RESET";

export const DELETE_VARIETY_REQUEST = "DELETE_VARIETY_REQUEST";
export const DELETE_VARIETY_SUCCESS = "DELETE_VARIETY_SUCCESS";
export const DELETE_VARIETY_FAIL = "DELETE_VARIETY_FAIL";
export const DELETE_VARIETY_RESET = "DELETE_VARIETY_RESET";
